when:
  event:
    - push
    - manual

matrix:
  RENOVATE_CONFIG_FILE:
    - default.json5
    - renovate.json5

steps:
  lint:
    image: renovate/renovate:latest
    pull: true
    commands:
      - renovate-config-validator
    environment:
      LOG_LEVEL: debug
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 400Mi
            cpu: 800m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
