when:
  event:
    - push
    - manual

matrix:
  RENOVATE_CONFIG_FILE:
    - default.json
    - renovate.json

steps:
  lint:
    image: renovate/renovate:latest@sha256:17affa39ace8dbb78177caab39cf25851249a1381bcbb4f6fd108372128af1b9
    pull: true
    commands:
      - renovate-config-validator
    environment:
      LOG_LEVEL: debug
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 400Mi
            cpu: 800m
