when:
  event:
    - cron
    - push
    - manual

steps:
  renovate-dry:
    image: renovate/renovate:38
    environment:
      github_com_token:
        from_secret: github_com_token
      private_key:
        from_secret: private_key
      aws_acccess_key_id:
        from_secret: aws_acccess_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      RENOVATE_PLATFORM: github
      RENOVATE_DRY_RUN: full
      LOG_LEVEL: debug
      RENOVATE_CONFIG_FILE: default.json
      RENOVATE_REPOSITORY_CACHE_TYPE: s3://cynkra-renovate-cache/github/
      RENOVATE_REPOSITORY_CACHE: enabled
      AWS_REGION: eu-central-1

    pull: true
    commands:
      - echo -e "$PRIVATE_KEY" > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    when:
      - event: push
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1800Mi
            cpu: 100m
          limits:
            memory: 3000Mi
            cpu: 1000m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

  renovate:
    image: renovate/renovate:38
    pull: true
    environment:
      github_com_token:
        from_secret: github_com_token
      private_key:
        from_secret: private_key
      aws_acccess_key_id:
        from_secret: aws_acccess_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      LOG_LEVEL: debug
      RENOVATE_PLATFORM: github
      RENOVATE_CONFIG_FILE: default.json
      RENOVATE_REPOSITORY_CACHE_TYPE: s3://cynkra-renovate-cache/github/
      RENOVATE_REPOSITORY_CACHE: enabled
      AWS_REGION: eu-central-1

    commands:
      - echo -e "$PRIVATE_KEY" > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    when:
      - event: cron
        cron: renovate
      - event: manual
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1800Mi
            cpu: 100m
          limits:
            memory: 3000Mi
            cpu: 1000m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
