when:
  event:
    - cron
    - push
    - manual

steps:
  renovate-dry:
    image: renovate/renovate:latest
    secrets: [ private_key ]
    pull: true
    commands:
      - echo $PRIVATE_KEY > /tmp/private-key.pem
      - npm -g install github-app-installation-token
      - renovate --username renovate-cynkra[bot] --token $(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private-key.pem) $${CI_REPO}
    environment:
      - RENOVATE_PLATFORM=github
      - RENOVATE_DRY_RUN=full
      - LOG_LEVEL=debug
    when:
      - event: push
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1100Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m

  renovate:
    image: renovate/renovate:latest
    secrets: [ private_key ]
    pull: true
    commands:
      - echo $PRIVATE_KEY > /tmp/private-key
      - npm -g install github-app-installation-token
      - export RENOVATE_TOKEN=$(npm run github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private-key)
      - renovate $${CI_REPO}
    environment:
      - RENOVATE_PLATFORM=github
    when:
      - event: cron
        cron: renovate
      - event: manual
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1100Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m
