when:
  event:
    - cron
    - push
    - manual

steps:
  renovate-dry:
    image: renovate/renovate:latest
    secrets: [ private_key, github_com_token ]
    pull: true
    commands:
      - echo -e "$PRIVATE_KEY" > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    environment:
      - RENOVATE_PLATFORM=github
      - RENOVATE_DRY_RUN=full
      - LOG_LEVEL=debug
      - RENOVATE_CONFIG_FILE=default.json
      - RENOVATE_REDIS_URL=redis://redis-cluster-prod.rdrc1b.clustercfg.euc1.cache.amazonaws.com:6379
    when:
      - event: push
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1100Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m

  renovate:
    image: renovate/renovate:latest
    secrets: [ private_key, github_com_token ]
    pull: true
    commands:
      - echo -e "$PRIVATE_KEY" > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    environment:
      - RENOVATE_PLATFORM=github
      - RENOVATE_CONFIG_FILE=default.json
      - RENOVATE_REDIS_URL=redis://redis-cluster-prod.rdrc1b.clustercfg.euc1.cache.amazonaws.com:6379
    when:
      - event: cron
        cron: renovate
      - event: manual
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1100Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m
