when:
  event:
    - cron
    - push
    - manual

steps:
  get-token:
    image: ghcr.io/yyewolf/woodpecker-plugins/github-app-token
    settings:
      github_app_id: 382538
      github_installation_id: 41217779
      github_private_key_pem:
        from_secret: private_key
      output_file: .github_token

  renovate-dry:
    image: renovate/renovate:43
    environment:
      aws_acccess_key_id:
        from_secret: aws_acccess_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      RENOVATE_PLATFORM: github
      RENOVATE_DRY_RUN: full
      LOG_LEVEL: info
      RENOVATE_CONFIG_FILE: default.json
      RENOVATE_REPOSITORY_CACHE_TYPE: s3://cynkra-renovate-cache/github/
      RENOVATE_REPOSITORY_CACHE: enabled
      AWS_REGION: eu-central-1

    pull: true
    commands:
      - renovate --token $(cat .github_token) $${CI_REPO}
    when:
      - event: push
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 3000Mi
            cpu: 100m
          limits:
            memory: 4000Mi
            cpu: 1000m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"

  renovate:
    image: renovate/renovate:43
    pull: true
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      aws_acccess_key_id:
        from_secret: aws_acccess_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      LOG_LEVEL: info
      RENOVATE_PLATFORM: github
      RENOVATE_CONFIG_FILE: default.json
      RENOVATE_REPOSITORY_CACHE_TYPE: s3://cynkra-renovate-cache/github/
      RENOVATE_REPOSITORY_CACHE: enabled
      AWS_REGION: eu-central-1

    commands:
      - echo -e $${PRIVATE_KEY} > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - export GITHUB_TOKEN=$RENOVATE_TOKEN
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    when:
      - event: cron
        cron: renovate
      - event: manual
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 3000Mi
            cpu: 100m
          limits:
            memory: 4000Mi
            cpu: 1000m
        tolerations:
          - key: "CI"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
