when:
  event:
    - cron
    - push
    - manual

steps:
  renovate-dry:
    image: renovate/renovate:37@sha256:17affa39ace8dbb78177caab39cf25851249a1381bcbb4f6fd108372128af1b9
    secrets: [ private_key, github_com_token, aws_access_key_id, aws_secret_access_key ]
    pull: true
    commands:
      - echo -e "$PRIVATE_KEY" > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    environment:
      - RENOVATE_PLATFORM=github
      - RENOVATE_DRY_RUN=full
      - LOG_LEVEL=debug
      - RENOVATE_CONFIG_FILE=default.json
      - RENOVATE_REPOSITORY_CACHE_TYPE=s3://cynkra-renovate-cache/github/
      - RENOVATE_REPOSITORY_CACHE=enabled
      - AWS_REGION=eu-central-1
    when:
      - event: push
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1100Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m

  renovate:
    image: renovate/renovate:37@sha256:17affa39ace8dbb78177caab39cf25851249a1381bcbb4f6fd108372128af1b9
    secrets: [ private_key, github_com_token, aws_access_key_id, aws_secret_access_key ]
    pull: true
    commands:
      - echo -e "$PRIVATE_KEY" > /tmp/private_key.pem
      # https://github.com/gagoar/github-app-installation-token
      - export RENOVATE_TOKEN=$(npx github-app-installation-token --appId 382538 --installationId 41217779 --privateKeyLocation /tmp/private_key.pem)
      - echo $RENOVATE_TOKEN
      - renovate $${CI_REPO}
    environment:
      - LOG_LEVEL=debug
      - RENOVATE_PLATFORM=github
      - RENOVATE_CONFIG_FILE=default.json
      - RENOVATE_REPOSITORY_CACHE_TYPE=s3://cynkra-renovate-cache/github/
      - RENOVATE_REPOSITORY_CACHE=enabled
      - AWS_REGION=eu-central-1
    when:
      - event: cron
        cron: renovate
      - event: manual
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 1100Mi
            cpu: 100m
          limits:
            memory: 2000Mi
            cpu: 1000m
